
export const DEFAULT_SCHOOLS = [
  {
    name: "University of British Columbia",
    logo: "/lovable-uploads/c33828a1-9c0c-4b97-bfdf-ebec721b736e.png",
    program: "Engineering",
    programType: "degree",
    website: "https://engineering.ubc.ca/",
    province: "bc",
    admissionGPA: 3.83,
    admissionRate: 43,
    tuitionDomestic: 7846,
    tuitionInternational: 60622,
    placementRate: 95,
    averageIncome: 80000,
    imageURL: "/lovable-uploads/c33828a1-9c0c-4b97-bfdf-ebec721b736e.png",
    worldRanking: 34,
    graduateEmployabilityScore: 95,
    entranceDifficulty: "High",
    institutionType: "Public University"
  },
  {
    name: "British Columbia Institute of Technology (BCIT)",
    logo: "/lovable-uploads/d5b2677f-869b-4f23-ae7b-8f2ffdac0406.png",
    program: "Information Technology Management",
    programType: "diploma",
    website: "https://www.bcit.ca/",
    province: "bc",
    admissionGPA: 3.25,
    admissionRate: 50,
    tuitionDomestic: 5500,
    tuitionInternational: 18500,
    placementRate: 92,
    averageIncome: 70000,
    imageURL: "/lovable-uploads/d5b2677f-869b-4f23-ae7b-8f2ffdac0406.png",
    worldRanking: 120,
    graduateEmployabilityScore: 92,
    entranceDifficulty: "Medium",
    institutionType: "Polytechnic Institute"
  },
  // Additional schools follow the same pattern
  {
    name: "Simon Fraser University (SFU)",
    logo: "/lovable-uploads/23a8b5bf-5d39-4994-b080-b15ae4f8a454.png",
    program: "Business Administration",
    programType: "degree",
    website: "https://beedie.sfu.ca/",
    province: "bc",
    admissionGPA: 3.65,
    admissionRate: 40,
    tuitionDomestic: 7200,
    tuitionInternational: 33000,
    placementRate: 90,
    averageIncome: 75000,
    imageURL: "/lovable-uploads/23a8b5bf-5d39-4994-b080-b15ae4f8a454.png",
    worldRanking: 65,
    graduateEmployabilityScore: 90,
    entranceDifficulty: "High",
    institutionType: "Public University"
  }
]
