
// This file provides a mapping of school names to their logo paths

// Map of school names (lowercase) to their logo file paths
export const schoolLogoMap: Record<string, string> = {
  // Canadian Universities
  "mcgill": "/logos/McGill University.jpg",
  "mcgill university": "/logos/McGill University.jpg",
  "ubc": "/logos/University of British Columbia.png",
  "university of british columbia": "/logos/University of British Columbia.png",
  "sfu": "/logos/Simon Fraser University.jpg",
  "simon fraser": "/logos/Simon Fraser University.jpg",
  "simon fraser university": "/logos/Simon Fraser University.jpg",
  "bcit": "/logos/BCIT.jpg",
  "british columbia institute of technology": "/logos/BCIT.jpg",
  "university of toronto": "/logos/University of Toronto.jpg",
  "toronto": "/logos/University of Toronto.jpg",
  "university of waterloo": "/logos/University of Waterloo.jpg",
  "waterloo": "/logos/University of Waterloo.jpg",
  "concordia": "/logos/Concordia.jpeg",
  "concordia university": "/logos/Concordia.jpeg",
  "university of calgary": "/logos/University of Calgary.jpg", 
  "calgary": "/logos/University of Calgary.jpg",
  "university of manitoba": "/logos/University of Manitoba.jpg",
  "manitoba": "/logos/University of Manitoba.jpg",
  "university of saskatchewan": "/logos/University of Saskatchewan.jpg",
  "saskatchewan": "/logos/University of Saskatchewan.jpg",
  "sask polytechnic": "/logos/Saskatchewan.jpeg", // Changed key to avoid duplication
  "university of alberta": "/logos/University of Alberta.jpg", 
  "alberta": "/logos/University of Alberta.jpg",
  "university of western ontario": "/logos/Western University.jpg",
  "western": "/logos/Western University.jpg",
  "western university": "/logos/Western University.jpg",
  "queen's": "/logos/Queen's University.jpg",
  "queen's university": "/logos/Queen's University.jpg",
  "queens university": "/logos/Queen's University.jpg",
  "york": "/logos/York University.jpg",
  "york university": "/logos/York University.jpg",
  "toronto metropolitan": "/logos/Toronto Metropolitan University.jpg",
  "toronto metropolitan university": "/logos/Toronto Metropolitan University.jpg",
  "ryerson": "/logos/Toronto Metropolitan University.jpg",
  "ryerson university": "/logos/Toronto Metropolitan University.jpg",
  "mount royal": "/logos/Mount Royal University.jpg",
  "mount royal university": "/logos/Mount Royal University.jpg",
  "university of victoria": "/logos/University of Victoria.jpg",
  "victoria": "/logos/University of Victoria.jpg",
  "university of ottawa": "/logos/University of Ottawa.jpg",
  "ottawa": "/logos/University of Ottawa.jpg",
  "dalhousie": "/logos/Dalhousie University.jpeg",
  "dalhousie university": "/logos/Dalhousie University.jpeg",
  "macewan": "/logos/MacEwan University.jpg",
  "macewan university": "/logos/MacEwan University.jpg",
  "grant macewan": "/logos/MacEwan University.jpg",
  "grant macewan university": "/logos/MacEwan University.jpg",
  "university of regina": "/logos/University of Regina.jpg",
  "regina": "/logos/University of Regina.jpg",
  "university of windsor": "/logos/University of Windsor.jpg",
  "windsor": "/logos/University of Windsor.jpg",
  "carleton": "/logos/Carleton University.jpg",
  "carleton university": "/logos/Carleton University.jpg",
  "memorial": "/logos/Memorial University.jpg",
  "memorial university": "/logos/Memorial University.jpg",
  "university of new brunswick": "/logos/University of New Brunswick.png",
  "new brunswick": "/logos/University of New Brunswick.png",
  "nait": "/logos/NAIT.jpeg",
  "northern alberta institute of technology": "/logos/NAIT.jpeg",
  "phoenix": "/logos/University of Phoenix.jpg",
  "university of phoenix": "/logos/University of Phoenix.jpg",
  
  // Canadian Colleges
  "seneca": "/logos/Seneca College.jpg",
  "seneca college": "/logos/Seneca College.jpg",
  "red river": "/logos/Red River College.png",
  "red river college": "/logos/Red River College.png",
  "vanier": "/logos/Vanier College.jpg",
  "vanier college": "/logos/Vanier College.jpg",
  "saskatchewan polytechnic": "/logos/Saskatchewan.jpeg", // This was a duplicate key
  "sait": "/logos/SAIT.png",
  "sait polytechnic": "/logos/SAIT.png",
  "southern new hampshire university": "/logos/Southern New Hampshire University.jpeg",
  "southern new hampshire": "/logos/Southern New Hampshire University.jpeg",
  "algonquin college": "/logos/Algonquin College.jpg",
  "algonquin": "/logos/Algonquin College.jpg",
  "athabasca university": "/logos/Athabasca University.jpeg",
  "athabasca": "/logos/Athabasca University.jpeg",
  "cdi college": "/logos/CDI College.jpg",
  "cdi": "/logos/CDI College.jpg",
  "nova scotia community college": "/logos/Nova Scotia Community College.jpg",
  "nscc": "/logos/Nova Scotia Community College.jpg",
  "saint mary's university": "/logos/Saint Mary's University.png",
  "saint mary": "/logos/Saint Mary's University.png",
  "saint mary's": "/logos/Saint Mary's University.png",
  "vancouver film school": "/logos/Vancouver Film School.jpg",
  "vfs": "/logos/Vancouver Film School.jpg",
  "langara": "/logos/Langara College.png",
  "langara college": "/logos/Langara College.png",
  "centennial": "/logos/Centennial College.jpg",
  "centennial college": "/logos/Centennial College.jpg",
  "george brown": "/logos/George Brown College.jpg",
  "george brown college": "/logos/George Brown College.jpg",
  "humber": "/logos/Humber College.jpg",
  "humber college": "/logos/Humber College.jpg",
  "sheridan": "/logos/Sheridan College.jpg",
  "sheridan college": "/logos/Sheridan College.jpg",
  "conestoga": "/logos/Conestoga College.jpg",
  "conestoga college": "/logos/Conestoga College.jpg",
  "douglas": "/logos/Douglas College.jpg",
  "douglas college": "/logos/Douglas College.jpg",
};

// A list of fallback logos in case a school name isn't found in the mapping
export const logoList = [
  "/logos/University of Toronto.jpg",
  "/logos/Simon Fraser University.jpg",
  "/logos/Seneca College.jpg",
  "/logos/Dalhousie University.jpeg",
  "/logos/Saskatchewan.jpeg",
];

// Default logo as global fallback
export const defaultLogo = "/logos/University of Toronto.jpg";
