
// This file provides a mapping of school names to their logo paths
// For local development with files on your PC, use relative paths

// Map of school names (lowercase) to their logo file paths
export const schoolLogoMap: Record<string, string> = {
  // Canadian Universities
  "mcgill": "/logos/Concordia.jpeg",
  "mcgill university": "/logos/Concordia.jpeg",
  "ubc": "/logos/Simon Fraser University.jpg",
  "university of british columbia": "/logos/Simon Fraser University.jpg",
  "sfu": "/logos/Simon Fraser University.jpg",
  "simon fraser": "/logos/Simon Fraser University.jpg",
  "simon fraser university": "/logos/Simon Fraser University.jpg",
  "bcit": "/logos/CDI College.jpg",
  "british columbia institute of technology": "/logos/CDI College.jpg",
  "university of toronto": "/logos/University of Toronto.jpg",
  "toronto": "/logos/University of Toronto.jpg",
  "university of waterloo": "/logos/University of Toronto.jpg",
  "waterloo": "/logos/University of Toronto.jpg",
  "concordia": "/logos/Concordia.jpeg",
  "concordia university": "/logos/Concordia.jpeg",
  "university of calgary": "/logos/University of Saskatchewan.jpg", 
  "calgary": "/logos/University of Saskatchewan.jpg",
  "university of manitoba": "/logos/University of Manitoba.jpg",
  "manitoba": "/logos/University of Manitoba.jpg",
  "university of saskatchewan": "/logos/University of Saskatchewan.jpg",
  "saskatchewan": "/logos/Saskatchewan.jpeg",
  "university of alberta": "/logos/University of Saskatchewan.jpg", 
  "alberta": "/logos/University of Saskatchewan.jpg",
  "university of western ontario": "/logos/University of Toronto.jpg",
  "western": "/logos/University of Toronto.jpg",
  "western university": "/logos/University of Toronto.jpg",
  "queen's": "/logos/Dalhousie University.jpeg",
  "queen's university": "/logos/Dalhousie University.jpeg",
  "queens university": "/logos/Dalhousie University.jpeg",
  "york": "/logos/University of Toronto.jpg",
  "york university": "/logos/University of Toronto.jpg",
  "toronto metropolitan": "/logos/University of Toronto.jpg",
  "toronto metropolitan university": "/logos/University of Toronto.jpg",
  "ryerson": "/logos/University of Toronto.jpg",
  "ryerson university": "/logos/University of Toronto.jpg",
  "mount royal": "/logos/University of Manitoba.jpg",
  "mount royal university": "/logos/University of Manitoba.jpg",
  "university of victoria": "/logos/Simon Fraser University.jpg",
  "victoria": "/logos/Simon Fraser University.jpg",
  "university of ottawa": "/logos/University of Toronto.jpg",
  "ottawa": "/logos/University of Toronto.jpg",
  "dalhousie": "/logos/Dalhousie University.jpeg",
  "dalhousie university": "/logos/Dalhousie University.jpeg",
  "macewan": "/logos/University of Manitoba.jpg",
  "macewan university": "/logos/University of Manitoba.jpg",
  "grant macewan": "/logos/University of Manitoba.jpg",
  "grant macewan university": "/logos/University of Manitoba.jpg",
  "university of regina": "/logos/Saskatchewan.jpeg",
  "regina": "/logos/Saskatchewan.jpeg",
  "university of windsor": "/logos/University of Toronto.jpg",
  "windsor": "/logos/University of Toronto.jpg",
  "carleton": "/logos/University of Toronto.jpg",
  "carleton university": "/logos/University of Toronto.jpg",
  "memorial": "/logos/Dalhousie University.jpeg",
  "memorial university": "/logos/Dalhousie University.jpeg",
  "university of new brunswick": "/logos/Dalhousie University.jpeg",
  "new brunswick": "/logos/Dalhousie University.jpeg",
  
  // Canadian Colleges
  "seneca": "/logos/Seneca College.jpg",
  "seneca college": "/logos/Seneca College.jpg",
  "red river": "/logos/Nova Scotia Community College.jpg",
  "red river college": "/logos/Nova Scotia Community College.jpg",
  "vanier": "/logos/Algonquin College.jpg",
  "vanier college": "/logos/Algonquin College.jpg",
  "saskatchewan polytechnic": "/logos/Saskatchewan.jpeg",
  "sait": "/logos/CDI College.jpg",
  "sait polytechnic": "/logos/CDI College.jpg",
  "southern new hampshire university": "/logos/Southern New Hampshire University.jpeg",
  "algonquin college": "/logos/Algonquin College.jpg",
  "athabasca university": "/logos/Athabasca University.jpeg",
  "cdi college": "/logos/CDI College.jpg",
  "nova scotia community college": "/logos/Nova Scotia Community College.jpg",
  "saint mary's university": "/logos/Saint Mary's University.png",
  "vancouver film school": "/logos/Vancouver Film School.jpg"
};

// A list of fallback logos in case a school name isn't found in the mapping
export const logoList = [
  "/logos/University of Toronto.jpg",
  "/logos/Simon Fraser University.jpg",
  "/logos/Seneca College.jpg",
  "/logos/Dalhousie University.jpeg",
  "/logos/Saskatchewan.jpeg",
];

// Default logo as global fallback
export const defaultLogo = "/logos/University of Toronto.jpg";
